// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: wms.proto

package wms_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReportAGVTaskRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgvId          string                 `protobuf:"bytes,1,opt,name=agv_id,json=agvId,proto3" json:"agv_id,omitempty"`
	InboundOrderId string                 `protobuf:"bytes,2,opt,name=inbound_order_id,json=inboundOrderId,proto3" json:"inbound_order_id,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReportAGVTaskRequest) Reset() {
	*x = ReportAGVTaskRequest{}
	mi := &file_wms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAGVTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAGVTaskRequest) ProtoMessage() {}

func (x *ReportAGVTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAGVTaskRequest.ProtoReflect.Descriptor instead.
func (*ReportAGVTaskRequest) Descriptor() ([]byte, []int) {
	return file_wms_proto_rawDescGZIP(), []int{0}
}

func (x *ReportAGVTaskRequest) GetAgvId() string {
	if x != nil {
		return x.AgvId
	}
	return ""
}

func (x *ReportAGVTaskRequest) GetInboundOrderId() string {
	if x != nil {
		return x.InboundOrderId
	}
	return ""
}

func (x *ReportAGVTaskRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ReportAGVTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportAGVTaskResponse) Reset() {
	*x = ReportAGVTaskResponse{}
	mi := &file_wms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAGVTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAGVTaskResponse) ProtoMessage() {}

func (x *ReportAGVTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAGVTaskResponse.ProtoReflect.Descriptor instead.
func (*ReportAGVTaskResponse) Descriptor() ([]byte, []int) {
	return file_wms_proto_rawDescGZIP(), []int{1}
}

func (x *ReportAGVTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportAGVTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_wms_proto protoreflect.FileDescriptor

const file_wms_proto_rawDesc = "" +
	"\n" +
	"\twms.proto\x12\x03wms\"o\n" +
	"\x14ReportAGVTaskRequest\x12\x15\n" +
	"\x06agv_id\x18\x01 \x01(\tR\x05agvId\x12(\n" +
	"\x10inbound_order_id\x18\x02 \x01(\tR\x0einboundOrderId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"K\n" +
	"\x15ReportAGVTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2]\n" +
	"\n" +
	"WMSService\x12O\n" +
	"\x16ReportAGVTaskCompleted\x12\x19.wms.ReportAGVTaskRequest\x1a\x1a.wms.ReportAGVTaskResponseB<Z:github.com/devil/wmss/agv/internal/core/contracts/wms_grpcb\x06proto3"

var (
	file_wms_proto_rawDescOnce sync.Once
	file_wms_proto_rawDescData []byte
)

func file_wms_proto_rawDescGZIP() []byte {
	file_wms_proto_rawDescOnce.Do(func() {
		file_wms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wms_proto_rawDesc), len(file_wms_proto_rawDesc)))
	})
	return file_wms_proto_rawDescData
}

var file_wms_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_wms_proto_goTypes = []any{
	(*ReportAGVTaskRequest)(nil),  // 0: wms.ReportAGVTaskRequest
	(*ReportAGVTaskResponse)(nil), // 1: wms.ReportAGVTaskResponse
}
var file_wms_proto_depIdxs = []int32{
	0, // 0: wms.WMSService.ReportAGVTaskCompleted:input_type -> wms.ReportAGVTaskRequest
	1, // 1: wms.WMSService.ReportAGVTaskCompleted:output_type -> wms.ReportAGVTaskResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wms_proto_init() }
func file_wms_proto_init() {
	if File_wms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wms_proto_rawDesc), len(file_wms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wms_proto_goTypes,
		DependencyIndexes: file_wms_proto_depIdxs,
		MessageInfos:      file_wms_proto_msgTypes,
	}.Build()
	File_wms_proto = out.File
	file_wms_proto_goTypes = nil
	file_wms_proto_depIdxs = nil
}
