// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: wms.proto

package wms_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WMSService_ReportAGVTaskCompleted_FullMethodName = "/wms.WMSService/ReportAGVTaskCompleted"
)

// WMSServiceClient is the client API for WMSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WMSServiceClient interface {
	ReportAGVTaskCompleted(ctx context.Context, in *ReportAGVTaskRequest, opts ...grpc.CallOption) (*ReportAGVTaskResponse, error)
}

type wMSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWMSServiceClient(cc grpc.ClientConnInterface) WMSServiceClient {
	return &wMSServiceClient{cc}
}

func (c *wMSServiceClient) ReportAGVTaskCompleted(ctx context.Context, in *ReportAGVTaskRequest, opts ...grpc.CallOption) (*ReportAGVTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportAGVTaskResponse)
	err := c.cc.Invoke(ctx, WMSService_ReportAGVTaskCompleted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WMSServiceServer is the server API for WMSService service.
// All implementations must embed UnimplementedWMSServiceServer
// for forward compatibility.
type WMSServiceServer interface {
	ReportAGVTaskCompleted(context.Context, *ReportAGVTaskRequest) (*ReportAGVTaskResponse, error)
	mustEmbedUnimplementedWMSServiceServer()
}

// UnimplementedWMSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWMSServiceServer struct{}

func (UnimplementedWMSServiceServer) ReportAGVTaskCompleted(context.Context, *ReportAGVTaskRequest) (*ReportAGVTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportAGVTaskCompleted not implemented")
}
func (UnimplementedWMSServiceServer) mustEmbedUnimplementedWMSServiceServer() {}
func (UnimplementedWMSServiceServer) testEmbeddedByValue()                    {}

// UnsafeWMSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WMSServiceServer will
// result in compilation errors.
type UnsafeWMSServiceServer interface {
	mustEmbedUnimplementedWMSServiceServer()
}

func RegisterWMSServiceServer(s grpc.ServiceRegistrar, srv WMSServiceServer) {
	// If the following call panics, it indicates UnimplementedWMSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WMSService_ServiceDesc, srv)
}

func _WMSService_ReportAGVTaskCompleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportAGVTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WMSServiceServer).ReportAGVTaskCompleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WMSService_ReportAGVTaskCompleted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WMSServiceServer).ReportAGVTaskCompleted(ctx, req.(*ReportAGVTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WMSService_ServiceDesc is the grpc.ServiceDesc for WMSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WMSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wms.WMSService",
	HandlerType: (*WMSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportAGVTaskCompleted",
			Handler:    _WMSService_ReportAGVTaskCompleted_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wms.proto",
}
