// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: agv.proto

package agv_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Coordinate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	mi := &file_agv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_agv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.
func (*Coordinate) Descriptor() ([]byte, []int) {
	return file_agv_proto_rawDescGZIP(), []int{0}
}

func (x *Coordinate) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Coordinate) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Waypoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *Coordinate            `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Waypoint) Reset() {
	*x = Waypoint{}
	mi := &file_agv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Waypoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Waypoint) ProtoMessage() {}

func (x *Waypoint) ProtoReflect() protoreflect.Message {
	mi := &file_agv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Waypoint.ProtoReflect.Descriptor instead.
func (*Waypoint) Descriptor() ([]byte, []int) {
	return file_agv_proto_rawDescGZIP(), []int{1}
}

func (x *Waypoint) GetPosition() *Coordinate {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Waypoint) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type ExecutePlanRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgvId          string                 `protobuf:"bytes,1,opt,name=agv_id,json=agvId,proto3" json:"agv_id,omitempty"`
	InboundOrderId string                 `protobuf:"bytes,2,opt,name=inbound_order_id,json=inboundOrderId,proto3" json:"inbound_order_id,omitempty"`
	WmsGrpcUrl     string                 `protobuf:"bytes,3,opt,name=wms_grpc_url,json=wmsGrpcUrl,proto3" json:"wms_grpc_url,omitempty"`
	Waypoints      []*Waypoint            `protobuf:"bytes,4,rep,name=waypoints,proto3" json:"waypoints,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecutePlanRequest) Reset() {
	*x = ExecutePlanRequest{}
	mi := &file_agv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePlanRequest) ProtoMessage() {}

func (x *ExecutePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePlanRequest.ProtoReflect.Descriptor instead.
func (*ExecutePlanRequest) Descriptor() ([]byte, []int) {
	return file_agv_proto_rawDescGZIP(), []int{2}
}

func (x *ExecutePlanRequest) GetAgvId() string {
	if x != nil {
		return x.AgvId
	}
	return ""
}

func (x *ExecutePlanRequest) GetInboundOrderId() string {
	if x != nil {
		return x.InboundOrderId
	}
	return ""
}

func (x *ExecutePlanRequest) GetWmsGrpcUrl() string {
	if x != nil {
		return x.WmsGrpcUrl
	}
	return ""
}

func (x *ExecutePlanRequest) GetWaypoints() []*Waypoint {
	if x != nil {
		return x.Waypoints
	}
	return nil
}

type ExecutePlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	AgvId         string                 `protobuf:"bytes,2,opt,name=agv_id,json=agvId,proto3" json:"agv_id,omitempty"`
	Steps         int32                  `protobuf:"varint,3,opt,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutePlanResponse) Reset() {
	*x = ExecutePlanResponse{}
	mi := &file_agv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutePlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePlanResponse) ProtoMessage() {}

func (x *ExecutePlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePlanResponse.ProtoReflect.Descriptor instead.
func (*ExecutePlanResponse) Descriptor() ([]byte, []int) {
	return file_agv_proto_rawDescGZIP(), []int{3}
}

func (x *ExecutePlanResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecutePlanResponse) GetAgvId() string {
	if x != nil {
		return x.AgvId
	}
	return ""
}

func (x *ExecutePlanResponse) GetSteps() int32 {
	if x != nil {
		return x.Steps
	}
	return 0
}

var File_agv_proto protoreflect.FileDescriptor

const file_agv_proto_rawDesc = "" +
	"\n" +
	"\tagv.proto\x12\x03agv\"(\n" +
	"\n" +
	"Coordinate\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\"O\n" +
	"\bWaypoint\x12+\n" +
	"\bposition\x18\x01 \x01(\v2\x0f.agv.CoordinateR\bposition\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\"\xa4\x01\n" +
	"\x12ExecutePlanRequest\x12\x15\n" +
	"\x06agv_id\x18\x01 \x01(\tR\x05agvId\x12(\n" +
	"\x10inbound_order_id\x18\x02 \x01(\tR\x0einboundOrderId\x12 \n" +
	"\fwms_grpc_url\x18\x03 \x01(\tR\n" +
	"wmsGrpcUrl\x12+\n" +
	"\twaypoints\x18\x04 \x03(\v2\r.agv.WaypointR\twaypoints\"Z\n" +
	"\x13ExecutePlanResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x15\n" +
	"\x06agv_id\x18\x02 \x01(\tR\x05agvId\x12\x14\n" +
	"\x05steps\x18\x03 \x01(\x05R\x05steps2U\n" +
	"\x11AGVControlService\x12@\n" +
	"\vExecutePlan\x12\x17.agv.ExecutePlanRequest\x1a\x18.agv.ExecutePlanResponseB<Z:github.com/devil/wmss/agv/internal/core/contracts/agv_grpcb\x06proto3"

var (
	file_agv_proto_rawDescOnce sync.Once
	file_agv_proto_rawDescData []byte
)

func file_agv_proto_rawDescGZIP() []byte {
	file_agv_proto_rawDescOnce.Do(func() {
		file_agv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agv_proto_rawDesc), len(file_agv_proto_rawDesc)))
	})
	return file_agv_proto_rawDescData
}

var file_agv_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_agv_proto_goTypes = []any{
	(*Coordinate)(nil),          // 0: agv.Coordinate
	(*Waypoint)(nil),            // 1: agv.Waypoint
	(*ExecutePlanRequest)(nil),  // 2: agv.ExecutePlanRequest
	(*ExecutePlanResponse)(nil), // 3: agv.ExecutePlanResponse
}
var file_agv_proto_depIdxs = []int32{
	0, // 0: agv.Waypoint.position:type_name -> agv.Coordinate
	1, // 1: agv.ExecutePlanRequest.waypoints:type_name -> agv.Waypoint
	2, // 2: agv.AGVControlService.ExecutePlan:input_type -> agv.ExecutePlanRequest
	3, // 3: agv.AGVControlService.ExecutePlan:output_type -> agv.ExecutePlanResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_agv_proto_init() }
func file_agv_proto_init() {
	if File_agv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agv_proto_rawDesc), len(file_agv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agv_proto_goTypes,
		DependencyIndexes: file_agv_proto_depIdxs,
		MessageInfos:      file_agv_proto_msgTypes,
	}.Build()
	File_agv_proto = out.File
	file_agv_proto_goTypes = nil
	file_agv_proto_depIdxs = nil
}
