// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: agv.proto

package agv_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AGVControlService_ExecutePlan_FullMethodName = "/agv.AGVControlService/ExecutePlan"
)

// AGVControlServiceClient is the client API for AGVControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AGVControlServiceClient interface {
	ExecutePlan(ctx context.Context, in *ExecutePlanRequest, opts ...grpc.CallOption) (*ExecutePlanResponse, error)
}

type aGVControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAGVControlServiceClient(cc grpc.ClientConnInterface) AGVControlServiceClient {
	return &aGVControlServiceClient{cc}
}

func (c *aGVControlServiceClient) ExecutePlan(ctx context.Context, in *ExecutePlanRequest, opts ...grpc.CallOption) (*ExecutePlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutePlanResponse)
	err := c.cc.Invoke(ctx, AGVControlService_ExecutePlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AGVControlServiceServer is the server API for AGVControlService service.
// All implementations must embed UnimplementedAGVControlServiceServer
// for forward compatibility.
type AGVControlServiceServer interface {
	ExecutePlan(context.Context, *ExecutePlanRequest) (*ExecutePlanResponse, error)
	mustEmbedUnimplementedAGVControlServiceServer()
}

// UnimplementedAGVControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAGVControlServiceServer struct{}

func (UnimplementedAGVControlServiceServer) ExecutePlan(context.Context, *ExecutePlanRequest) (*ExecutePlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecutePlan not implemented")
}
func (UnimplementedAGVControlServiceServer) mustEmbedUnimplementedAGVControlServiceServer() {}
func (UnimplementedAGVControlServiceServer) testEmbeddedByValue()                           {}

// UnsafeAGVControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AGVControlServiceServer will
// result in compilation errors.
type UnsafeAGVControlServiceServer interface {
	mustEmbedUnimplementedAGVControlServiceServer()
}

func RegisterAGVControlServiceServer(s grpc.ServiceRegistrar, srv AGVControlServiceServer) {
	// If the following call panics, it indicates UnimplementedAGVControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AGVControlService_ServiceDesc, srv)
}

func _AGVControlService_ExecutePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutePlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AGVControlServiceServer).ExecutePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AGVControlService_ExecutePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AGVControlServiceServer).ExecutePlan(ctx, req.(*ExecutePlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AGVControlService_ServiceDesc is the grpc.ServiceDesc for AGVControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AGVControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agv.AGVControlService",
	HandlerType: (*AGVControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecutePlan",
			Handler:    _AGVControlService_ExecutePlan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agv.proto",
}
